name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@0.2.0
        with:
          version:  1.4.30
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: app/build/output/apk/debug/app-debug.apk
          

